export const PRODUCTIONS_REPOSITORY = Symbol('PRODUCTIONS_REPOSITORY')
export const PRODUCTIONS_TRANSLATES_REPOSITORY = Symbol('PRODUCTIONS_TRANSLATES_REPOSITORY')

export const PRODUCTIONS_SERVICES = Symbol('PRODUCTIONS_SERVICES')
