export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY')
export const CATEGORY_TRANSLATES_REPOSITORY = Symbol('CATEGORY_TRANSLATES_REPOSITORY')

export const CATEGORY_SERVICE = Symbol('CATEGORY_SERVICE')
