version: '3'
name: 'hzb'

services:
    hzb-postgres:
        image: postgres:11
        restart: always

        ports:
            - 3303:5432

        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASS}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_DB}

    hzb-redis:
        image: 'redis:4-alpine'
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
            - '6379:6379'

    hzb-minio:
        hostname: hzb-minio
        image: minio/minio:RELEASE.2021-09-18T18-09-59Z
        container_name: hzb-minio

        volumes:
            - './hzb/data/:/data'
            - './hzb/config:/root/.minio'

        ports:
            - 5003:9000
            - 5004:9001
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        command: server --console-address ":9001"  /data

    hzb-createbuckets:
        image: minio/mc
        depends_on:
            - hzb-minio
        entrypoint: >
            /bin/sh -c " sleep 10; /usr/bin/mc config host add data http://${MINIO_HOST}:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; /usr/bin/mc mb data/${MINIO_BUCKET}; /usr/bin/mc policy set public data/${MINIO_BUCKET}; exit 0; "
    hzb-imgproxy:
        image: 'darthsim/imgproxy:latest'
        ports:
            - '5005:8080'
        depends_on:
            - hzb-minio
        links:
            - hzb-minio
        environment:
            IMGPROXY_KEY: ${IMGPROXY_KEY}
            IMGPROXY_SALT: ${IMGPROXY_SALT}
            IMGPROXY_MAX_SRC_FILE_SIZE: 10485760
