export const PROJECTS_REPOSITORY = Symbol('PROJECTS_REPOSITORY')
export const PROJECTS_SERVICES = Symbol('PROJECTS_SERVICES')

export const PROJECTS_TRANSLATES_REPOSITORY = Symbol('PROJECTS_TRANSLATES_REPOSITORY')

export const PROJECTS_DETAILS_REPOSITORY = Symbol('PROJECTS_DETAILS_REPOSITORY')
