export const PRODUCTS_REPOSITORY = Symbol('PRODUCTS_REPOSITORY')
export const PRODUCTS_TRANSLATES_REPOSITORY = Symbol('PRODUCTS_TRANSLATES_REPOSITORY')
export const PRODUCTS_TO_CATEGORY = Symbol('PRODUCTS_TO_CATEGORY')

export const PRODUCTS_SERVICE = Symbol('PRODUCTS_SERVICE')
