export const DISTRIBUTIONS_REPOSITORY = Symbol('DISTRIBUTIONS_REPOSITORY')
export const DISTRIBUTIONS_TRANSLATES_REPOSITORY = Symbol('DISTRIBUTIONS_TRANSLATES_REPOSITORY')

export const DISTRIBUTIONS_SERVICES = Symbol('DISTRIBUTIONS_SERVICES')
