export const QUALITY_REPOSITORY = Symbol('QUALITY_REPOSITORY')
export const QUALITY_TRANSLATES_REPOSITORY = Symbol('QUALITY_TRANSLATES_REPOSITORY')

export const QUALITY_SERVICE = Symbol('QUALITY_SERVICE')
