export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY')

export const PASSWORD_HASH_SALT = Symbol('PASSWORD_HASH_SALT')

export const USERS_SERVICE = Symbol('USERS_SERVICE')
export const USERS_PASSWORDS_SERVICE = Symbol('USERS_PASSWORDS_SERVICE')
