export const LABOLATORY_REPOSITORY = Symbol('LABOLATORY_REPOSITORY')
export const LABOLATORY_TRANSLATES_REPOSITORY = Symbol('LABOLATORY_TRANSLATES_REPOSITORY')

export const LABOLATORY_SERVICE = Symbol('LABOLATORY_SERVICE')
