export enum Regions {
	Cherkasy = 'ch',
	Chernihiv = 'chv',
	Chernivtsi = 'chi',
	Dnipro = 'do',
	Donetsk = 'dk',
	IvanoFrankivsk = 'if',
	Kharkiv = 'kv',
	Kherson = 'kn',
	Khmelnytskyi = 'ki',
	Kropyvnytskyi = 'kri',
	Kyiv = 'ky',
	Luhansk = 'lk',
	Lviv = 'lv',
	Mykolaiv = 'mv',
	Odesa = 'oa',
	Poltava = 'pa',
	Rivne = 're',
	Sumy = 'sy',
	Ternopil = 'tl',
	Vinnytsia = 'va',
	Lutsk = 'luk',
	Uzhhorod = 'ud',
	Zaporizhzhia = 'za',
	Zhytomyr = 'zr',
}
