export const AWARDS_REPOSITORIES = Symbol('AWARDS_REPOSITORIES')
export const AWARDS_TRANSLATES_REPOSITORIES = Symbol('AWARDS_TRANSLATES_REPOSITORIES')

export const AWARDS_SERVICE = Symbol('AWARDS_SERVICE')
