export const CLIENTS_REPOSITORY = Symbol('CLIENTS_REPOSITORY')
export const CLIENTS_TRANSLATES_REPOSITORY = Symbol('CLIENTS_TRANSLATES_REPOSITORY')

export const CLIENTS_SERVICES = Symbol('CLIENTS_SERVICES')
