export * from '../interfaces'

export const CONTACTS_TAB_REPOSITORY = Symbol('CONTACTS_TAB_REPOSITORY')
export const CONTACTS_DEPARTMENT_REPOSITORY = Symbol('CONTACTS_DEPARTMENT_REPOSITORY')
export const CONTACTS_SUBDEPARTMENT_REPOSITORY = Symbol('CONTACTS_SUBDEPARTMENT_REPOSITORY')
export const CONTACTS_TAB_TRANSLATION_REPOSITORY = Symbol('CONTACTS_TAB_TRANSLATION_REPOSITORY')
export const CONTACTS_DEPARTMENT_TRANSLATION_REPOSITORY = Symbol('CONTACTS_DEPARTMENT_TRANSLATION_REPOSITORY')
export const CONTACTS_SUBDEPARTMENT_TRANSLATION_REPOSITORY = Symbol('CONTACTS_SUBDEPARTMENT_TRANSLATION_REPOSITORY')
export const CONTACTS_SERVICE = Symbol('CONTACTS_SERVICE')