export * from './auth/auth.module'
export * from './account/account.module'
export * from './news/news.module'
export * from './awards/awards.module'
export * from './distributors/distributors.module'
export * from './productions/productions.module'
export * from './projects/projects.module'
export * from './quality/quality.module'
export * from './labolatory/labolatory.module'
export * from './partner/partner.module'
export * from './productions/productions.module'
export * from "./categories/categories.module"
export * from "./feedbacks/feedbacks.module"
export * from "./contacts/contacts.module"