export const PARTNER_SERVICE = Symbol('PARTNER_SERVICE')
export const PARTNER_REPOSITORY = Symbol('PARTNER_REPOSITORY')

export const PARTNER_TRANSLATE_REPOSITORY = Symbol('PARTNER_TRANSLATE_REPOSITORY')